[package]
name = "live_dynamic_auto_post"
version = "0.1.0"
edition = "2024"

[dependencies]
bpi-rs = "0.1.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
toml = "0.9.8"
tracing = "0.1.43"
unescape = "0.1.0"
