# 配置文件
# 直播间ID
roomid = 26320007
# 转发动态所需文本
repost_text = "转发动态"
# Cookie
bili_jct = "your_bili_jct_here"
dede_user_id = "your_dede_user_id_here"
dede_user_id_ckmd5 = "your_dede_user_id_ckmd5_here"  
sessdata = "your_sessdata_here"
buvid3 = "your_buvid3_here"